language: php

sudo: false

cache: false

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*@dev
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*@dev

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.4.*" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;
  - rm -Rf Tests/Functional/var/cache/test

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.4.*" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ] && [ "$SYMFONY_VERSION" == "4.4.*" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
