language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=3.4.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 5.6
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" == "3.0.*" ]; then composer require "twig/twig:^1.31" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS
  - cat composer.lock

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
